// Subresource Integrity hashes for the scripts the site loads, so every one can
// carry an `integrity` attribute (groundwork for enforcing
// `Integrity-Policy: blocked-destinations=(script)`). Three shapes:
//
//   sri("/x.js")   — committed files under public/, hashed from their bytes at
//                    build time (Node/SSG, never shipped), so the hash can't
//                    drift from what we serve.
//   pagefind*      — the Pagefind runtime + component UI, emitted by
//                    `pagefind --site dist` AFTER the Astro build, so they can't
//                    be hashed here: committed constants, guarded by
//                    scripts/check-integrity.mjs. Version-stable (no site data).
//   webmcp         — generated per-build from spec content (see src/lib/webmcp.ts),
//                    hashed from its exact generated bytes.
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";

/** sha384 SRI hash (`sha384-<base64>`) of raw bytes or a UTF-8 string. */
export function sriOf(bytes: Buffer | string): string {
  return `sha384-${createHash("sha384").update(bytes).digest("base64")}`;
}

const fileCache = new Map<string, string>();

/**
 * SRI hash of a committed file under public/, addressed by its served path
 * (e.g. "/search.js" → public/search.js). Memoised across the many page renders.
 */
export function sri(servedPath: string): string {
  let value = fileCache.get(servedPath);
  if (!value) {
    value = sriOf(readFileSync(join(process.cwd(), "public", servedPath)));
    fileCache.set(servedPath, value);
  }
  return value;
}

/** Pagefind runtime (/pagefind/pagefind.js), pulled in via dynamic import(). */
export const pagefindIntegrity =
  "sha384-oWDbZtddm6imqwKspZTD9CKGLSoOfvCVazIPigUPcSHDVGymVJvsBvvI3lFJNjm2";

/** Pagefind Component UI (/pagefind/pagefind-component-ui.js), loaded via <script src>. */
export const pagefindComponentUiIntegrity =
  "sha384-sgK6d6muVu9zgs2S4M4GuLq6M9fV5OMX7x2wloOZiDmbOgYhQa+tf8Ukevo/kjeq";

/**
 * Inline import map attaching pagefindIntegrity to the dynamic import of
 * pagefind.js — the only way to give a dynamically imported module integrity
 * metadata. Rendered verbatim in <head> via set:html; its sha256 is allow-listed
 * in the CSP script-src in public/_headers. If this serialisation changes,
 * recompute that hash:
 *   printf '%s' '<the JSON>' | openssl dgst -sha256 -binary | openssl base64 -A
 */
export const pagefindImportMap = JSON.stringify({
  integrity: {
    "/pagefind/pagefind.js": pagefindIntegrity,
  },
});
